steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - getmarketDetails_function
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --allow-unauthenticated 
  
  args:
  - functions
  - deploy
  - pushDataToFireStore
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --allow-unauthenticated 
  
