steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - getMarketDetails
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated 

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - pushToFireStoreData
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated 
  
