steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'getmarketDetails_function',
      '--trigger-http',
      '--runtime', 'python37',
      '--region', 'us-central1',
      '--source=.', 'getmarketDetails_function'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'pushDataToFireStore',
      '--trigger-http',
      '--runtime', 'python37',
      '--region', 'us-central1',
      '--source=.', 'pushDataToFireStore'
    ]
    
    
